SistemaIntegralIngresos/Models/Campus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaIntegralIngresos.Models
{
    public class Campus
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Código")]
        public String Code { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public String Name { get; set; }
        [Display(Name = "Detalles")]
        public String Details { get; set; }

  
    }
}

SistemaIntegralIngresos/Controllers/CampusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaIntegralIngresos.Models;
using Microsoft.VisualStudio.QualityTools.UnitTestFramework;

namespace SistemaIntegralIngresos.Controllers
{
    public class CampusController : Controller
    {
        private SIIDbContext db = new SIIDbContext();
        private ICampus repository;

        public CampusController(ICampus repository) 
        {
            this.repository = repository;
        }

        public CampusController()
        {
            this.repository = new CampusOperationRepo();
        }

        //
        // GET: /Campus/

        public ActionResult Index()
        {
            return View(db.Campus.ToList());
        }

        //
        // GET: /Campus/Details/5

        public ActionResult Details(int id = 0)
        {
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        //
        // GET: /Campus/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Campus/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Campus.Add(campus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campus);
        }

        //
        // GET: /Campus/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        //
        // POST: /Campus/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        //
        // GET: /Campus/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Campus campus = db.Campus.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        //
        // POST: /Campus/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campus campus = db.Campus.Find(id);
            db.Campus.Remove(campus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

       
        public ActionResult GetAllCampus()
        {
            //test CampusController
            var Campus = repository.GetAllCampus();
            return View(Campus);
        }

        public Boolean InsertCampus(Campus campus )
        {
            return repository.InsertCampus(campus);
        }
        
        public Boolean DeleteCampus(int id )
        {
            return repository.DeleteCampus(id);
        }

        public Campus FindByID(int id )
        {
            return repository.FindByID(id);
        }

        public Boolean EditCampus(Campus campus)
        {
            return repository.EditCampus(campus);
        }


    }
}

SistemaIntegralIngresos/Views/Campus/Create.cshtml
@model SistemaIntegralIngresos.Models.Campus

@{
    ViewBag.ModuleTitle = "Crear campus";
}
<div class="row">
    <div class="small-8 small-offset-2 columns">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Campus</legend>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Code, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Code)
                        @Html.ValidationMessageFor(model => model.Code)
                    </div>
                </div>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Name, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Details, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Details)
                        @Html.ValidationMessageFor(model => model.Details)
                    </div>
                </div>
                
                <div class="row">
                    <div class="small-6 small-offset-1">
                        <ul class="button-group">
                            <li><input type="submit" value="Crear" class="small button" /></li>
                            <li>@Html.ActionLink("Regresar a la Lista", "Index", "Campus", htmlAttributes: new { @class = "small button" })</li>
                        </ul>
                    </div>
                </div>
            </fieldset>
        }
    </div>
  
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaIntegralIngresos/Views/Campus/Delete.cshtml
@model SistemaIntegralIngresos.Models.Campus

@{
    ViewBag.ModuleTitle = "Eliminar un campus";
}
<div class="row">
    <div class="small-8 small-offset-2 columns">
        <h4>¿Está seguro que desea eliminar el campus?</h4>
        <fieldset>
            <legend>Campus</legend>
            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Code)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Code)
                </div>
            </div>

            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Name)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </div>

            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Details)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Details)
                </div>
            </div>
           

        </fieldset>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <ul class="button-group">
                <li><input type="submit" value="Eliminar" class="small alert button" /></li>
                <li>@Html.ActionLink("Regresar a la lista", "Index", "Campus", htmlAttributes: new { @class = "small button" })</li>
            </ul>
        }
    </div>
</div>

SistemaIntegralIngresos/Views/Campus/Details.cshtml
@model SistemaIntegralIngresos.Models.Campus

@{
    ViewBag.Title = "Detalle de campus";
}

<div class="row">
    <div class="small-8 small-offset-2 columns">
        <h4>¿Está seguro que desea eliminar el campus?</h4>
        <fieldset>
            <legend>Campus</legend>
            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Code)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Code)
                </div>
            </div>

            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Name)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </div>

            <div class="row">
                <div class="small-2 columns">
                    <span class="label">@Html.DisplayNameFor(model => model.Details)</span>
                </div>
                <div class="small-10 columns">
                    @Html.DisplayFor(model => model.Details)
                </div>
            </div>


        </fieldset>
       
        <ul class="button-group">
            <li>@Html.ActionLink("Editar", "Edit", "Campus", new { id = Model.Id }, htmlAttributes: new { @class = "small button" })</li>
            <li>@Html.ActionLink("Regresar a la lista", "Index", "Campus", htmlAttributes: new { @class = "small button" })</li>
        </ul>
        
    </div>
</div>

SistemaIntegralIngresos/Views/Campus/Edit.cshtml
@model SistemaIntegralIngresos.Models.Campus

@{
    ViewBag.ModuleTitle = "Editar campus";
}

<div class="row">
    <div class="small-8 small-offset-2 columns">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Campus</legend>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Code, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Code)
                        @Html.ValidationMessageFor(model => model.Code)
                    </div>
                </div>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Name, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
                <div class="row">
                    <div class="small-2 columns">
                        @Html.LabelFor(model => model.Details, new { @class = "right inline" })
                    </div>
                    <div class="small-10 columns">
                        @Html.EditorFor(model => model.Details)
                        @Html.ValidationMessageFor(model => model.Details)
                    </div>
                </div>

                <div class="row">
                    <div class="small-6 small-offset-1">
                        <ul class="button-group">
                            <li><input type="submit" value="Editar" class="small button" /></li>
                            <li>@Html.ActionLink("Regresar a la Lista", "Index", "Campus", htmlAttributes: new { @class = "small button" })</li>
                        </ul>
                    </div>
                </div>
            </fieldset>
        }
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaIntegralIngresos/Views/Campus/Index.cshtml
@model IEnumerable<SistemaIntegralIngresos.Models.Campus>

@{
    ViewBag.ModuleTitle = "Administrar campus";
}
<div class="row">
    <div class="small-8 small-offset-2 columns">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Details)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Details)
                    </td>
                    <td>
                        <i class="fi-clipboard-pencil medium"></i> @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                        <i class="fi-eye medium"></i> @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                        <i class="fi-x medium"></i> @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
        <div class="row">
            @Html.ActionLink("Crear nuevo campus", "Create", "Campus", htmlAttributes: new { @class = "small button" })
        </div>
    </div>
</div>